import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
import { evaluate, type EvaluationResult } from "./evaluate.js";

/** CLI: run the benchmark in both modes and write RESULTS.md. */

const pct = (v: number) => (v * 100).toFixed(1) + "%";

function section(result: EvaluationResult): string {
  const lines: string[] = [];
  lines.push(`## Mode: ${result.mode}`);
  lines.push("");
  lines.push("| Class | Support | TP | FP | FN | Precision | Recall | F1 |");
  lines.push("|---|---|---|---|---|---|---|---|");
  for (const c of result.overall.perClass) {
    lines.push(
      `| ${c.cls} | ${c.support} | ${c.tp} | ${c.fp} | ${c.fn} | ` +
        `${pct(c.precision)} | ${pct(c.recall)} | ${pct(c.f1)} |`,
    );
  }
  const m = result.overall.micro;
  lines.push(
    `| **micro** | | ${m.tp} | ${m.fp} | ${m.fn} | **${pct(m.precision)}** | **${pct(m.recall)}** | **${pct(m.f1)}** |`,
  );
  lines.push("");
  lines.push(`- Leak rate (invariant + high severity): **${pct(result.overall.leakRate)}**`);
  lines.push(`- Invariant-class leaks: **${result.invariantLeaks.length}**`);
  lines.push(`- False alarms on declared negatives: **${result.overall.falseAlarms.length}**`);
  if (result.overall.leaks.length > 0) {
    lines.push("");
    lines.push("Missed (the honest gap list):");
    for (const l of result.overall.leaks) {
      lines.push(`- ${l.cls} (${l.severity}): ${l.note ?? "no note"}`);
    }
  }
  lines.push("");
  return lines.join("\n");
}

const shield = evaluate("shield");
const fortress = evaluate("fortress");

const doc = [
  "# RedactBench-Web v0 results",
  "",
  "Structure-tier evaluation of the live policy engine over " +
    `${shield.captures.length} synthetic captures. Generated by \`npm run bench\`; ` +
    "do not edit by hand.",
  "",
  section(shield),
  section(fortress),
  "Notes:",
  "- v0 captures are structured (no pixels); PERSON_NAME and free-text ADDRESS",
  "  recall is a known Tier 0 gap that the NER tier addresses. It is listed,",
  "  not hidden.",
  "- Negatives (order ids, helplines, appointment dates, employee ids) count",
  "  as false alarms when masked; precision is measured, not assumed.",
  "",
].join("\n");

const out = join(fileURLToPath(new URL("..", import.meta.url)), "RESULTS.md");
writeFileSync(out, doc);
console.log(doc);
console.log(`written to ${out}`);
